(function() {var implementors = {};
implementors["embedded_graphics"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;u8&gt; for <a class=\"struct\" href=\"embedded_graphics/pixelcolor/struct.PixelColorU8.html\" title=\"struct embedded_graphics::pixelcolor::PixelColorU8\">PixelColorU8</a>",synthetic:false,types:["embedded_graphics::pixelcolor::PixelColorU8"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;u8&gt; for <a class=\"struct\" href=\"embedded_graphics/pixelcolor/struct.PixelColorU16.html\" title=\"struct embedded_graphics::pixelcolor::PixelColorU16\">PixelColorU16</a>",synthetic:false,types:["embedded_graphics::pixelcolor::PixelColorU16"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;u16&gt; for <a class=\"struct\" href=\"embedded_graphics/pixelcolor/struct.PixelColorU16.html\" title=\"struct embedded_graphics::pixelcolor::PixelColorU16\">PixelColorU16</a>",synthetic:false,types:["embedded_graphics::pixelcolor::PixelColorU16"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;u8&gt; for <a class=\"struct\" href=\"embedded_graphics/pixelcolor/struct.PixelColorU32.html\" title=\"struct embedded_graphics::pixelcolor::PixelColorU32\">PixelColorU32</a>",synthetic:false,types:["embedded_graphics::pixelcolor::PixelColorU32"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;u32&gt; for <a class=\"struct\" href=\"embedded_graphics/pixelcolor/struct.PixelColorU32.html\" title=\"struct embedded_graphics::pixelcolor::PixelColorU32\">PixelColorU32</a>",synthetic:false,types:["embedded_graphics::pixelcolor::PixelColorU32"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
