(function() {var implementors = {};
implementors["embedded_graphics"] = [{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"embedded_graphics/fonts/struct.Font6x8.html\" title=\"struct embedded_graphics::fonts::Font6x8\">Font6x8</a>&lt;'a&gt;",synthetic:false,types:["embedded_graphics::fonts::font6x8::Font6x8"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"embedded_graphics/primitives/circle/struct.Circle.html\" title=\"struct embedded_graphics::primitives::circle::Circle\">Circle</a>",synthetic:false,types:["embedded_graphics::primitives::circle::Circle"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"embedded_graphics/primitives/circle/struct.CircleIterator.html\" title=\"struct embedded_graphics::primitives::circle::CircleIterator\">CircleIterator</a>",synthetic:false,types:["embedded_graphics::primitives::circle::CircleIterator"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"embedded_graphics/primitives/line/struct.Line.html\" title=\"struct embedded_graphics::primitives::line::Line\">Line</a>",synthetic:false,types:["embedded_graphics::primitives::line::Line"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"embedded_graphics/primitives/rect/struct.Rect.html\" title=\"struct embedded_graphics::primitives::rect::Rect\">Rect</a>",synthetic:false,types:["embedded_graphics::primitives::rect::Rect"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"embedded_graphics/primitives/rect/struct.RectIterator.html\" title=\"struct embedded_graphics::primitives::rect::RectIterator\">RectIterator</a>",synthetic:false,types:["embedded_graphics::primitives::rect::RectIterator"]},];
implementors["embedded_hal"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"embedded_hal/spi/enum.Polarity.html\" title=\"enum embedded_hal::spi::Polarity\">Polarity</a>",synthetic:false,types:["embedded_hal::spi::Polarity"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"embedded_hal/spi/enum.Phase.html\" title=\"enum embedded_hal::spi::Phase\">Phase</a>",synthetic:false,types:["embedded_hal::spi::Phase"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"embedded_hal/spi/struct.Mode.html\" title=\"struct embedded_hal::spi::Mode\">Mode</a>",synthetic:false,types:["embedded_hal::spi::Mode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"embedded_hal/enum.Direction.html\" title=\"enum embedded_hal::Direction\">Direction</a>",synthetic:false,types:["embedded_hal::Direction"]},];
implementors["nb"] = [{text:"impl&lt;E:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"nb/enum.Error.html\" title=\"enum nb::Error\">Error</a>&lt;E&gt;",synthetic:false,types:["nb::Error"]},];
implementors["ssd1306"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"ssd1306/builder/struct.Builder.html\" title=\"struct ssd1306::builder::Builder\">Builder</a>",synthetic:false,types:["ssd1306::builder::Builder"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"ssd1306/displayrotation/enum.DisplayRotation.html\" title=\"enum ssd1306::displayrotation::DisplayRotation\">DisplayRotation</a>",synthetic:false,types:["ssd1306::displayrotation::DisplayRotation"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"ssd1306/prelude/enum.DisplaySize.html\" title=\"enum ssd1306::prelude::DisplaySize\">DisplaySize</a>",synthetic:false,types:["ssd1306::displaysize::DisplaySize"]},];
implementors["void"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"void/enum.Void.html\" title=\"enum void::Void\">Void</a>",synthetic:false,types:["void::Void"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
